-- CREATE DATABASE prompts_manager;
-- USE prompts_manager;
-- CREATE TABLE IF NOT EXISTS categories (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) UNIQUE NOT NULL, description TEXT );
-- CREATE TABLE IF NOT EXISTS prompts (id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(200) NOT NULL, content TEXT NOT NULL, category_id INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL);
-- CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role ENUM('user', 'admin') DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, status ENUM('active', 'blocked') DEFAULT 'active', user_id INT);
-- CREATE TABLE prompt_logs (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     user_id INT NOT NULL,
--     username VARCHAR(100) NOT NULL,
--     prompt_id INT NOT NULL,
--     action ENUM('CREATE','UPDATE','DELETE') NOT NULL,
--     field_name VARCHAR(50) NULL,   -- field that changed
--     old_value TEXT NULL,
--     new_value TEXT NULL,
--     message TEXT NULL,             -- optional description
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
--     FOREIGN KEY (prompt_id) REFERENCES prompts(id) ON DELETE CASCADE
-- );
-- CREATE TABLE user_sessions (
--     id INT AUTO_INCREMENT PRIMARY KEY,

--     user_id INT NOT NULL,
--     login_time DATETIME NOT NULL,
--     logout_time DATETIME NULL,

--     ip_address VARCHAR(45) NULL,
--     user_agent TEXT NULL,

--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );